# 编写自动化测试

Rust 设计时即高度重视程序正确性。但是正确性非常复杂，证明起来并不容易。Rust 的类型系统肩负了与正确性相关的大部分重担。但是类型系统不可能捕捉到所有非正确状况。因而，Rust 语言中内置了对编写自动化软件测试的支持。

例如，编写一个名为 `add_two` 的函数（用于将接收到的数字加 2 后返回），该函数接受一个整数作为参数并返回一个整数作为结果。当实现并编译这个函数时，Rust 会进行类型检查以及借用检查来确保这一点（ 没有将 `String` 值或者无效引用作为参数传递给此函数 ）。但是，Rust 无法检查函数会像我们预期的那样工作 - 返回参数与 2 的相加的结果而不是参数与 10 相加或者参数减去 50 后的结果！这正是测试起作用的地方。

我们可以编写用于断言的测试。当传递 3 给函数时，返回值是 5 。任何时候对代码作出修改后都可以通过运行这些测试以确保所有已知的正确行为没有发生变化。

测试是一项综合技能：单个章节无法涵盖编写良好测试的所有技术细节，此处着重介绍 Rust 提供的基础测试工具链。包括编写测试时可用的注解以及宏、运行测试时的默认行为以及选项，以及如何将测试组织划分为单元测试和集成测试。

## 如何编写测试

测试是用于验证非测试代码以预期方式工作的 Rust 函数。典型的，测试函数的函数体执行以下三种操作：

- 设置需要的数据或状态
- 运行测试代码
- 断言测试结果符合预期

Rust 为使用这些操作编写测试特别提供了支持，包括 `test` 属性，一些宏以及 `should_panic` 属性。

### 剖析测试函数

Rust 中的最简单的测试即一个带有 `test` 属性注解的函数。属性是与一块 Rust 代码相关的元数据。将一个普通函数窗转换为测试函数，在 `fn` 行之前添加元数据属性注解 `#[test]` 即可。当运行 `cargo test` 命令后，Rust 会构建一个测试执行程序来运行带有 `test` 属性的测试函数，并报告测试结果。

使用 Cargo 新建一个库项目时，会自动生成一个包含测试函数的测试模块。此模块使得在每次开始新项目的时候，无需翻查详细的测试函数结构及语法即可以开始编写测试。可以添加任意数量的额外测试函数及测试模块。

创建一个新的库项目：

```shell
$ cargo new adder --lib
     Created library `adder` project
$ cd adder
```

文件 “adder/src/lib.rs” 的内容：

```rust
#[cfg(test)] // 元数据属性注解
mod tests {
    #[test] // 元数据属性注解，表明 it_works 函数是一个测试函数
    fn it_works() {
        assert_eq!(2 + 2, 4); // 使用宏对逻辑进行断言
    }

    // tests 模块中也可以包含非测试函数帮助对常见情况进行设置或者运行常见操作
    fn helper() {
    }
}
```

`cargo test` 命令会运行项目中的所有测试：

```shell
$ cargo test
   Compiling adder v0.1.0 (file:///projects/adder)
    Finished dev [unoptimized + debuginfo] target(s) in 0.22 secs
     Running target/debug/deps/adder-ce99bcc2479f4607

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests adder

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

### 测试结果

Cargo 编译并运行测试。在 `Compiling`, `Finished` 以及 `Running` 之后是 `running 1 test` 行。再下一行则显示了生成的测试函数名 `it_works` 以及测试结果 `ok`。测试运行结果的整体概要紧跟其后。`test result: ok.` 表示所有的测试都通过了，`1 passed; 0 failed` 部分统计了测试通过或失败的数目。

由于现在还没有被标记为忽略的测试，所以测试结果中显示的是 `0 ignored`。同样的，没有被过滤的测试，所以测试结果中显示的是 `0 filtered out.`。

`0 measured` 统计数据用于测量性能的基准测试。基准测目前仅在 nightly 版本的 Rust 可用。参见 [the documentation about benchmark tests](https://doc.rust-lang.org/unstable-book/library-features/test.html)

测试输出中以 `Doc-tests adder` 开头的部分，是所有文档测试的结果。当前还没有文档测试，不过 Rust 会编译出现在 API 文档中的所有代码示例。这个功能有助于文档以及其中的代码保持同步。详情参见[“Documentation Comments as Tests”](https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#documentation-comments-as-tests)，此处暂时忽略对 `Doc-tests` 输出的介绍。

总结一下，测试结果包含代码测试结果、 文档测试结果两部分：

#### 代码测试结果

- `passed` 通过
- `failed` 失败
- `ignored` 忽略
- `measured` 针对性能基准测试，目前仅 Nightly 版本 Rust 可用
- `filtered` 过滤

#### 文档测试结果

Rust 会编译 API 文档中的代码示例，使文档和代码保持同步

#### 不同测试场景示例 - 改变测试函数签名

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn exploration() {
        assert_eq!(2 + 2, 4);
    }
}
```

输出：

```shell
running 1 test
test tests::exploration ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

#### 不同测试场景示例 - 包含失败情况的多个测试

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn exploration() {
        assert_eq!(2 + 2, 4);
    }

    #[test]
    fn another() {
        // 当测试函数中出现 Panic 时，测试失败
        // 主线程观察到某个测试线程失活，测试将会被标记为失败
        panic!("Make this test fail");
    }
}
```

输出：

```shell
running 2 tests
test tests::exploration ... ok
test tests::another ... FAILED

failures:

---- tests::another stdout ----
thread 'tests::another' panicked at 'Make this test fail', src/lib.rs:10:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    tests::another

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed
```

### 使用 assert! 宏检查结果

`assert!` 宏由标准库提供，在希望确保测试中某些情况为 `true` 时非常有用。使用 `assert!` 宏需要提供一个求值为布尔值的参数。如果值为 `true`，`assert!` 宏什么也不做，测试通过。如果值为 `false`，`assert!` 宏将调用会造成测试失败的 `panic!` 宏。`assert!` 宏用于检查代码是否以预期的方式运行。

文件 `src/lib.rs` 内容：

```rust
#[derive(Debug)]
pub struct Rectangle {
    length: u32,
    width: u32,
}

impl Rectangle {
    pub fn can_hold(&self, other: &Rectangle) -> bool {
        self.length > other.length && self.width > other.width
    }
}

#[cfg(test)]
// 内部模块 “tests”
mod tests {
    use super::*; // 将 tests 模块外的代码引入作用域

    #[test]
    fn larger_can_hold_smaller() {
        let larger = Rectangle { length: 8, width: 7 };
        let smaller = Rectangle { length: 5, width: 1 };

        assert!(larger.can_hold(&smaller));
    }

    #[test]
    fn smaller_cannot_hold_larger() {
        let larger = Rectangle { length: 8, width: 7 };
        let smaller = Rectangle { length: 5, width: 1 };

        assert!(!smaller.can_hold(&larger)); // 注意此处的取反操作
    }
}
```

测试结果：

```shell
running 2 tests
test tests::smaller_cannot_hold_larger ... ok
test tests::larger_can_hold_smaller ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

修改代码引入 BUG 之后：

```rust
impl Rectangle {
    pub fn can_hold(&self, other: &Rectangle) -> bool {
        self.width < other.width && self.length > other.length
    }
}
```

运行结果：

```shell
running 2 tests
test tests::smaller_cannot_hold_larger ... ok
test tests::larger_can_hold_smaller ... FAILED

failures:

---- tests::larger_can_hold_smaller stdout ----
    thread 'tests::larger_can_hold_smaller' panicked at 'assertion failed:
    larger.can_hold(&smaller)', src/lib.rs:22:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    tests::larger_can_hold_smaller

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

### 使用 `assert_eq!` 宏、 `assert_ne!` 宏测试相等

- 传递给 `assert_eq!` 宏的两个值相等时测试通过，反之失败
- 传递给 `assert_ne!` 宏的两个值不相等时测试通过，反之失败

```rust
# fn main() {}
pub fn add_two(a: i32) -> i32 {
    a + 2
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_adds_two() {
        assert_eq!(4, add_two(2));
    }
}
```

```shell
running 1 test
test tests::it_adds_two ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

引入 BUG：

```rust
fn main() {}
pub fn add_two(a: i32) -> i32 {
    a + 3
}
```

运行结果：

```shell
running 1 test
test tests::it_adds_two ... FAILED

failures:

---- tests::it_adds_two stdout ----
thread 'tests::it_adds_two' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `5`', src/lib.rs:11:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    tests::it_adds_two

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

其他语言和测试框架中，用来比较两个值相等的函数参数被称为 `expected` 和 `actual`，其命名顺序取决于指定参数的方式。在 Rust 中，它们被称为 `left` 以及 `right`，其命名顺序为期望值与测试代码生成的不相符的值。如果将比较代码写成 `assert_eq!(add_two(2), 4)`，那么测试失败信息将会显示 `assertion failed: (left == right)`， `left` 为 5，`right` 为 4。

`assert_ne!` 宏则会在两个值不相等的时候通过，相等的时候失败。适用于不确定会得到什么值但是确定代码按预期运行肯定不会得到某个值的情况。

`assert_eq!` 和 `assert_ne!` 宏在底层分别使用了 `==` 和 `!=`。当断言失败时，这些宏会使用调试格式打印出其参数，这意味着被比较的值必需实现了 `PartialEq` 和 `Debug` 特质。所有基本类型及大部分标准库类型都实现了这些特质。对于自定义的结构体和枚举，需要实现 `PartialEq` 才能断言它们的值是否相等。需要实现 `Debug` 才能在断言失败时打印它们的值。因为这两个特质都是派生特质，通常可以通过直接在自定义结构体或枚举上添加 `#[derive(PartialEq, Debug)]` 注解。具体细节可参考 [Derivable Traits](https://doc.rust-lang.org/book/appendix-03-derivable-traits.html)

### 添加自定义失败信息

可以向 `assert!`、`assert_eq!` 和 `assert_ne!` 宏传递包含自定义失败信息的可选参数，可选参数被传递给 `format!` 宏处理，所以可以传递一个包含 `{}` 占位符的格式字符串和需要放入占位符的值，自定义失败信息将在测试失败时被打印。自定义失败信息有助于记录断言的意义，当测试失败时可以更好的分析代码中的问题。

```rust
# fn main() {}
pub fn greeting(name: &str) -> String {
    format!("Hello {}!", name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn greeting_contains_name() {
        let result = greeting("Carol");

        // 在被测试函数的实现还不确定的情况下，
        // 相比断言整个返回值，仅断言返回值中包含输入参数的部分即可
        assert!(result.contains("Carol"));
    }
}
```

引入BUG：

```rust
pub fn greeting(name: &str) -> String {
    String::from("Hello!")
}
```

运行测试：

```shell
running 1 test
test tests::greeting_contains_name ... FAILED

failures:

---- tests::greeting_contains_name stdout ----
        thread 'tests::greeting_contains_name' panicked at 'assertion failed:
result.contains("Carol")', src/lib.rs:12:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    tests::greeting_contains_name
```

测试结果仅输出了断言失败的提示以及失败行号，没有更多可用的信息提供参考，此时正是自定义错误信息发挥作用的场景。

改进代码以包含更多详细提示信息：

```rust
#[test]
fn greeting_contains_name() {
    let result = greeting("Carol");
    assert!(
        // 使用可选参数以提供自定义失败信息
        result.contains("Carol"),
        "Greeting did not contain name, value was `{}`", result
    );
}
```

再次运行测试：

```shell
---- tests::greeting_contains_name stdout ----
        thread 'tests::greeting_contains_name' panicked at 'Greeting did not
contain name, value was `Hello!`', src/lib.rs:12:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

此时在测试输出中可以看到自定义失败信息，这有助于我们理解测试失败的具体原因。

### 使用 `should_panic` 检查 panic

除了测试代码是否返回期望值之外，测试代码是否按预期处理错误也很重要。

可通过为函数增加属性 `should_panic` 来实现此类测试，`should_panic` 属性在函数中的代码 `panic` 时会通过，反之失败。

```rust
# fn main() {}
pub struct Guess {
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }

        Guess {
            value
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[should_panic]
    fn greater_than_100() {
        Guess::new(200);
    }
}
```

测试通过：

```shell
running 1 test
test tests::greater_than_100 ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

引入BUG：

```rust

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1  {
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }

        Guess {
            value
        }
    }
}
```

测试结果失败：

```shell
running 1 test
test tests::greater_than_100 ... FAILED

failures:

failures:
    tests::greater_than_100

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

测试结果失败，也没有得到有用的信息，但是当我们观察测试函数时，会看到它使用了 `#[should_panic]` 注解，这表明被测试函数并没有引发 `panic`。

使用 `should_panic` 的测试函数的含义比较模糊，它仅仅表明代码会引发某种 `panic`，甚至在由于不同原因导致测试 `panic` 时 `should_panic` 测试也会通过，为了使 `should_panic` 测试结果更精确，可以给 `should_panic` 属性增加一个可选的 `expected` 参数，这种测试约束会确保错误信息中包含其提供的文本信息。

```rust
pub struct Guess {
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 {
            panic!("Guess value must be greater than or equal to 1, got {}.",
                   value);
        } else if value > 100 {
            panic!("Guess value must be less than or equal to 100, got {}.",
                   value);
        }

        Guess {
            value
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    // 测试会通过，因为 expected 参数提供的值是 Guess::new 函数 panic 信息的子串
    #[should_panic(expected = "Guess Value must be less than or equal to 100")]
    fn greater_than_100() {
        Guess::new(200);
    }
}
```

可以指定完整的预期 panic 信息，指定 expected 参数时如何选择取决于 panic 信息有多独特、动态以及希望测试有多精确。修改代码：

```rust
if value < 1 {
    panic!("Guess value must be less than or equal to 100, got {}.", value);
} else if value > 100 {
    panic!("Guess value must be greater than or equal to 1, got {}.", value);
}
```

测试结果：

```shell
running 1 test
test tests::greater_than_100 ... FAILED

failures:

---- tests::greater_than_100 stdout ----
        thread 'tests::greater_than_100' panicked at 'Guess value must be
greater than or equal to 1, got 200.', src/lib.rs:11:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
note: Panic did not include expected string 'Guess value must be less than or
equal to 100'

failures:
    tests::greater_than_100

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

测试失败，输出结果表明代码确实发生了 `panic`，但是 `panic` 信息中并没有包含 `expected` 提供的信息，有了这些信息，我们就可以检查测试失败的原因出在哪里了。

### 在测试中使用 `Result<T, E>`

可以使用 `Result<T, E>` ，以返回 `Err` 代替失败时 Panic 来编写测试函数。

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() -> Result<(), String> {
        if 2 + 2 == 4 {
            Ok(())
        } else {
            Err(String::from("two plus two does not equal four"))
        }
    }
}
```

在函数体中，当测试通过后返回 `Ok(())` 而不是调用 `assert_eq!` 宏，当测试失败时返回一个内部包含 `String` 的 `Err`。

编写此类返回 `Result<T, E>` 的测试可以在测试体中使用 ？操作符，如果测试中包含了返回一个 Err 变体的操作将会导致测试失败，那么使用 ？操作符更加简便。

注意：无法在使用 `Result<T, E>` 的测试函数上使用 `#[should_panic]` 注解。而是应当在测试失败时直接返回一个 `Err` 值。

## 运行测试

`cargo test` 在测试模式下编译代码并运行生成的二进制结果进行测试。

`cargo test` 生成的二进制文件默认行为：

- 并行运行所有测试，并捕捉测试运行期间生成的输出
- 阻止测试运行过程中的输出，提高测试结果相关输出的易读性

通过指定命令行参数可以改变 `cargo test` 的默认行为，可将一部分参数传递给 `cargo test`，另外一部分参数传递给生成的测试二进制文件。

```shell
# 显示 `cargo test` 命令的可用选项
cargo test --help
# 显示分隔符 `--` 之后的可用选项 ( 传递给生成的测试二进制文件 )
cargo test -- --help
```

### 以并行或者串行的方式运行测试

Rust 默认使用线程并行运行多个测试，这意味着测试会更快地结束运行，更快得到代码是否正常工作的反馈。由于测试是同时运行的，应当确保测试不能相互依赖，或依赖任何共享状态、共享环境（ 当前工作目录或环境变量 ）

如果不希望并行运行测试，或者想精确的设置线程数量，可以传参给测试二进制文件，例如：

```bash
# 设置测试线程数为 1，即不使用并行。这将花费更多时间，不过在有共享状态时，测试不会互扰。
cargo test -- --test-threads=1
```

### 显示函数输出

```rust
fn prints_and_returns_10(a: i32) -> i32 {
    println!("I got the value {}", a);
    10
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn this_test_will_pass() {
        let value = prints_and_returns_10(4);
        assert_eq!(10, value);
    }

    #[test]
    fn this_test_will_fail() {
        let value = prints_and_returns_10(8);
        assert_eq!(5, value);
    }
}
```

运行测试：

```shell
running 2 tests
test tests::this_test_will_pass ... ok
test tests::this_test_will_fail ... FAILED

failures:

---- tests::this_test_will_fail stdout ----
        I got the value 8
thread 'tests::this_test_will_fail' panicked
at 'assertion failed: `(left == right)`
  left: `5`,
 right: `10`', src/lib.rs:19:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    tests::this_test_will_fail

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

示例代码表明，测试通过时，测试运行过程中的标准输出会被 Rust 测试库截获，仅有表示测试通过的信息行会被输出。当测试失败时，测试运行期间的打印内容会随着测试结果中的失败信息部分一起输出。

如果希望看到通过测试的打印输出，可以通过传递参数来禁用截获输出的默认行为：

```rust
cargo test -- --nocapture
```

运行结果：

```shell
running 2 tests
I got the value 4
I got the value 8
test tests::this_test_will_pass ... ok
thread 'tests::this_test_will_fail' panicked at 'assertion failed: `(left == right)`
  left: `5`,
 right: `10`', src/lib.rs:19:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
test tests::this_test_will_fail ... FAILED

failures:

failures:
    tests::this_test_will_fail

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

注意，以上输出顺序为并行运行测试的结果，可以尝试使用 `--test-threads=1` 加 `--nocapture` 运行测试来对比观察输出。

### 运行部分测试

有时候，运行整个测试集会花费很长时间。当编写特定区域的代码时，只运行与该部分代码相关的测试会节省很多时间。这时可通过将测试函数的函数名（一个或多个）作为参数传递给 `cargo test` 来有选择的运行测试函数。

```rust
pub fn add_two(a: i32) -> i32 {
    a + 2
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn add_two_and_two() {
        assert_eq!(4, add_two(2));
    }

    #[test]
    fn add_three_and_two() {
        assert_eq!(5, add_two(3));
    }

    #[test]
    fn one_hundred() {
        assert_eq!(102, add_two(100));
    }
}
```

#### 默认运行测试

```shell
running 3 tests
test tests::add_two_and_two ... ok
test tests::add_three_and_two ... ok
test tests::one_hundred ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

#### 运行单个测试

```shell
$ cargo test one_hundred
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/adder-06a75b4a1f2515e9

running 1 test
test tests::one_hundred ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out
```

无法通过此方式指定多个测试的名称，只有第一个值会被 cargo test 使用。但是有其它运行多个测试的方式。

#### 过滤运行多个测试

可以指定测试函数的部分函数名，任何函数名与该值相匹配的测试函数将会被运行。

```shell
$ cargo test add
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/adder-06a75b4a1f2515e9

running 2 tests
test tests::add_two_and_two ... ok
test tests::add_three_and_two ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out
```

注意：测试所在的模块也是测试名的一部分，所以可以通过过滤模块名来运行一个模块中的所有测试

### 忽略某些测试

一些特定的测试非常耗时，很多时候希望能够在测试中将其排除。一一列举所有期望运行的测试作为参数的方式比较麻烦，更简单的方式是使用 `ignore` 属性对需要排除的测试进行标注。

```rust
#[test]
fn it_works() {
    assert_eq!(2 + 2, 4);
}

#[test]
#[ignore]
fn expensive_test() {
    // code that takes an hour to run
}
```

运行测试：

```shell
$ cargo test
   Compiling adder v0.1.0 (file:///projects/adder)
    Finished dev [unoptimized + debuginfo] target(s) in 0.24 secs
     Running target/debug/deps/adder-ce99bcc2479f4607

running 2 tests
test expensive_test ... ignored
test it_works ... ok

test result: ok. 1 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out
```

如果只希望运行被忽略的测试：

```shell
cargo test -- --ignored
```

运行测试：

```shell
$ cargo test -- --ignored
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/adder-ce99bcc2479f4607

running 1 test
test expensive_test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out
```

## 测试组织

测试是一门复杂的学科，其所使用的术语和组织方法因人而异。Rust 社区从两种主要分类来考量测试：单元测试、集成测试。单元测试较小，侧重于一次测试一个独立的模块，可测试私有接口。集成测试整体相对于我们编写的库来说是外部的，使用与其他外部代码相同的方式使用我们编写的代码，仅使用公开接口并且在一次测试中有可能对多个模块进行调用。

编写此两种测试对于确保所编写的库的各个组成部分能够像预期的那样单独或者一起工作非常重要。

### 单元测试

单元测试的目的是在与其他代码隔离的环境中测试每个代码单元，以便快速判断产生非预期行为的代码所在位置。

单元测试与其要测试的代码共同存放于 `src` 目录下的文件中。通常做法是在每个文件中创建包含测试函数的 `tests` 模块并使用 `cfg(test)` 标注。

#### 测试模块与模块注解 `cfg(test)`

`#[cfg(test)]` 注解告诉 Rust 只在执行 `cargo test` 时编译和运行测试代码，而不是运行 `cargo build` 时。由于不包含测试，在构建库的时候可以节省编译时间，减小编译产出的文件体积。集成测试单独存放于其他文件夹，所以不需要 `#[cfg(test)]` 注解，而单元测试与代码位于相同的文件中，所以需要使用 `#[cfg(test)]` 注解来指明它们不应该被包含进编译结果。

文件 src/lib.rc 内容：

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

上述示例代码即为自动生成的测试模块。`cfg` 属性表示 `configuration` ，告诉 Rust 在其之后的部分只能在给定某个配置选项之后才能被包含。在这个例子中，配置选项是 `test`，即 Rust 所提供的用于编译和运行测试的配置选项。通过使用 `cfg` 属性，Cargo 只会在我们主动使用 `cargo test` 运行测试时才编译测试代码。这包含了被标注为 `#[test]` 的函数，以及测试模块中可能存在的任何辅助函数。

#### 测试私有函数

测试社区中对于是否应当直接对私有函数进行测试还存在争议，并且测试私有函数在其他语言中很困难，甚至是不可能的。先不管倾向于何种测试思想，而 Rust 的私有规则确实允许测试私有函数。

文件 src/lib.rs 内容：

```rust
pub fn add_two(a: i32) -> i32 {
    internal_adder(a, 2)
}

// 私有函数
fn internal_adder(a: i32, b: i32) -> i32 {
    a + b
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn internal() {
        assert_eq!(4, internal_adder(2, 2));
    }
}
```

测试无非是一些 Rust 代码，而 tests 模块只是另一个模块，自然可以将 internal_adder 引入测试的作用域并进行调用。如果你不认为私有函数应当被测试，那么 Rust 也不会强制你这么做。

### 集成测试

在 Rust 中，集成测试对于需要测试的库来说完全是外部的，集成测试以其他外部代码相同的方式使用被测试的库，这意味着只能调用作为被测试库的公有接口的一部分的那些函数。集成测试的目的是测试库的多个部分能否一起正常工作。单独运行时没有问题的代码单元在集成在一起运行时可能会出现问题，所以集成测试的测试覆盖率也很重要。创建集成测试，首先需要一个 `tests` 目录。

#### `tests`目录

编写集成测试，需要在项目根目录创建 `tests` 目录，与 `src` 同级，Cargo 知道从 `tests` 目录中查找集成测试文件。在 `tests` 目录中可以创建任意数量的测试文件，Cargo 会将 `tests` 目录下的每个文件都当作单独的 `crate` 进行编译。

```rust
// tests/integration_test.rs
use adder;

#[test]
fn it_adds_two() {
    assert_eq!(4, adder::add_two(2));
}
```

集成测试文件需要在文件顶部添加 `use adder`，这与单元测试文件不同，因为每个集成测试文件都是单独的 Crate，所以需要将被测试的库导入每个集成测试 Crate 的作用域中。

集成测试文件中的代码不需要使用 `#[cfg(test)]` 进行标注, `tests` 目录受到 Cargo 的特殊对待，仅在运行 `cargo test` 时对此目录中的文件进行编译。

运行结果包含单元测试、集成测试、文档测试三部分输出：

```shell
$ cargo test
   Compiling adder v0.1.0 (file:///projects/adder)
    Finished dev [unoptimized + debuginfo] target(s) in 0.31 secs
     Running target/debug/deps/adder-abcabcabc

running 1 test
test tests::internal ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/integration_test-ce99bcc2479f4607

running 1 test
test it_adds_two ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests adder

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

与单元测试类似，添加测试函数到集成测试文件会在测试结果中对应的集成测试文件段落中产生更多的结果行。在测试结果中，每个集成测试文件都有属于自己的段落，因此，如果在 `tests` 目录中增加测试文件，那么在测试结果中就会相应地出现更多集成测试段落。

仍然可以通过指定测试函数名作为 `cargo test` 的参数来运行特定的集成测试函数：

```shell
cargo test internal
```

运行特定集成测试文件中的所有测试：

```shell
# 只运行集成测试 integration_test.rs 中的测试
$ cargo test --test integration_test
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/integration_test-952a27e0126bb565

running 1 test
test it_adds_two ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

#### 集成测试中的子模块

增加更多集成测试之后，可能想利用 `tests` 目录中的多个文件来帮助组织测试。例如，按照所测试的功能对测试函数进行分组。前文提到，`tests` 目录中的每个文件都被当作它自己独有的 crate 进行编译。

将每个集成测试文件当作它自己的 crate 对于创建像终端用户使用你的 crate 那样的单独作用域很有用。然而，这意味着 `tests` 目录中的文件并不像 `src` 目录中的文件那样共享相同的行为。

当有一组用于多个集成测试文件中的辅助函数，在将其提取为一个通用模块之后，`tests` 目录中文件的不同行为就变得显而易见了。例如，如果我们创建 `tests/common.rs` 文件并放入一个名为 setup 的函数，就可以在函数体中添加一些我们想要从多个测试文件中的多个测试函数中调用的代码：

```rust
// tests/common.rs
pub fn setup() {
    // 此处为设置代码，用于对你所编写的库进行集成测试
}
```

运行测试，会看到测试输出中出现了与 `common.rs` 文件有关的新段落。尽管此文件并不包含任何测试函数，我们也没有在任何地方调用 `setup` 函数：

```shell
running 1 test
test tests::internal ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/common-b8b07b6f1be2db70

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/integration_test-d993c68b431d39df

running 1 test
test it_adds_two ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests adder

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

我们只是想与其它集成测试文件共享一些代码，因此测试结果中出现包含 `running 0 tests` 显示的 `common` 并不是我们想要的。

为了避免在测试输出中出现 `common`，应当创建 `tests/common/mod.rs` 而不是创建 `tests/common.rs`。这是一种 Rust 能够理解的命名约定，以此方式命名文件告诉 Rust 不要将 `common` 模块作为一个集成测试文件对待。将 `setup` 函数代码移入 `tests/common/mod.rs` 文件中并删除 `tests/common.rs` 文件之后，测试输出中的 `common` 段落将不再出现。`tests` 目录子目录中的文件不会被当作单独的 Crate 编译或有对应的段落出现在测试输出中。因此，如果需要创建一些在多个集成测试文件都会用到的辅助函数，并希望将它们提取为通用模块，正确的做法应当是将代码创建到 `tests/common/` 目录。之后，可以从任意集成测试文件中使用该模块。示例如下：

```rust
// tests/integration_test.rs
use adder;

mod common;

#[test]
fn it_adds_two() {
    // 在集成测试中调用 common 模块（ tests/common ）中的 setup 函数
    common::setup();
    assert_eq!(4, adder::add_two(2));
}
```

#### 二进制 Crate 的集成测试

如果项目是只包含 `src/main.rs` 的二进制 Crate，并没有 `src/lib.rs` 文件，就无法在 `tests` 目录中创建集成测试并使用 `use` 声明语句将 `src/main.rs` 文件中定义的函数导入作用域。只有库 Crate 会暴露供其他 Crate 使用的函数，二进制 Crate 意味着其可以自主运行。

Rust 项目提供二进制的理由之一，在于二进制项目有一个可以对存在于 `src/lib.rs` 文件中的逻辑进行调用的简单的 `src/main.rs` 文件。使用这种结构，集成测试可以通过使用 `use` 来测试库 Crate，确保其重要功能可用，如果这些重要功能没有问题的话，那么剩下的 `src/main.rs` 中的少量代码也会正常工作而无需测试。
